services:
  app:
    build: .
    network_mode: host
    user: 'node'
    working_dir: /workspace
    volumes:
      - .:/workspace
      - npm-cache:/home/node/.npm
      - expo-state:/home/node/.expo
    environment:
      EXPO_NO_TELEMETRY: '1'
    stdin_open: true
    tty: true
    command: ['npx', 'expo', 'start']

volumes:
  npm-cache:
  expo-state:
